// Field manifest for FDA Form 3500 (MedWatch, Health Professional Voluntary
// Reporting). Enumerated directly from the current authoritative fillable PDF
// (fda.gov/media/76299/download, filename FDA_3500_Stat_Sec_Ext_09-15-2025.pdf)
// via its AcroForm widgets, not guessed or search-derived — see docs/design.md
// "Data shape" and Issue #3.

export type FormSection = "A" | "B" | "C" | "D" | "E" | "F" | "G";

export const FORM_3500_SECTIONS: Record<FormSection, string> = {
  A: "Patient Information",
  B: "Adverse Event, Product Problem (or Product Use Error)",
  C: "Product Availability",
  D: "Suspect Products",
  E: "Suspect Medical Device",
  F: "Other (Concomitant) Medical Products",
  G: "Reporter",
};

export type FormFieldType = "text" | "date" | "checkbox" | "enum";

export interface FormFieldSpec {
  id: string;
  section: FormSection;
  pdfFieldName: string;
  label: string;
  type: FormFieldType;
  required: boolean;
  options?: string[];
}

const UNIT_OPTIONS: string[] = [" ", "AS NECESSARY - AN", "BECQUEREL(S) - BQ", "CURIE(S) - CI", "CYCLICAL - CYC", "DOSAGE FORM - DF", "DROP(S) - GTT", "GIGABECQUEREL(S) - GBQ", "GRAM(S) - GM", "INTERNATIONAL UNIT(S) - IU", "IU(1,000,000S) - MIU", "IU(1000S) - KIU", "IU/KILOGRAM - IU/KG", "KILOBECQUEREL(S) - KBQ", "KILOGRAM(S) - KG", "LITRE(S) - L", "MEGABECQUEREL(S) - MBQ", "MICROCURIE(S) - UCI", "MICROGRAM(S) - UGM", "MICROGRAM(S)/KILOGRAM(S) -UGM/KG", "MICROGRAM(S)/MICROGRAM(S) - UGM/UGM", "MICROGRAM(S)/SQ. METERS - UGM/SQ M", "MICROGRAMS/HOUR - UGM/HR", "MICROLITRE(S) - UL", "MICROMOLE(S) - UMOLE", "MILLICURIE(S) - MCI", "MILLIEQUIVALENT(S) - MEQ", "MILLIGRAM(S) - MG", "MILLIGRAM(S)/KILOGRAM(S) - MG/KG", "MILLIGRAM(S)/SQ. METERS - MG/SQ M", "MILLIGRAMS/MILLIGRAMS - MG/MG", "MILLIGRAMS/MILLILITRES - MG/ML", "MILLILITRE(S) - ML", "MILLIMOLE(S) - MMOLE", "MOLE(S) - MOLE", "NANOCURIE(S) - NCI", "NANOGRAM(S) - NGM", "PERCENT - %", "PICOGRAM(S) - PGM", "TOTAL - TOT", "TRIMESTER - TRI", "UNKNOWN - UNK"];

const FREQUENCY_OPTIONS: string[] = [" ", "BID", "Daily", "HS", "PRN", "QID", "TID", "Other"];

const ROUTE_OPTIONS: string[] = [" ", "Auricular (otic)", "Buccal", "Cutaneous", "Dental", "Endocervical", "Endosinusial", "Endotracheal", "Epidural", "Extra-amniotic", "Hemodialysis", "Intra corpus cavernosum", "Intra-amniotic", "Intra-arterial", "Intra-articular", "Intra-uterine", "Intracardiac", "Intracavernous", "Intracerebral", "Intracervical", "Intracisternal", "Intracorneal", "Intracoronary", "Intradermal", "Intradiscal (intraspinal)", "Intrahepatic", "Intralesional", "Intralymphatic", "Intramedullar (bone marrow)", "Intrameningeal", "Intramuscular", "Intraocular", "Intrapericardial", "Intraperitoneal", "Intrapleural", "Intrasynovial", "Intrathecal", "Intrathoracic", "Intratracheal", "Intratumor", "Intravenous (not otherwise specified)", "Intravenous bolus", "Intravenous drip", "Intravesical", "Iontophoresis", "Nasal", "Occlusive dressing technique", "Ophthalmic", "Oral", "Oropharingeal", "Parenteral", "Periarticular", "Perineural", "Rectal", "Respiratory (inhalation)", "Retrobulbar", "Subcutaneous", "Subdermal", "Sublingual", "Sunconjunctival", "Topical", "Transdermal", "Transmammary", "Transplacental", "Unknown", "Urethral", "Vaginal", "Other"];

const DURATION_UNIT_OPTIONS: string[] = [" ", "Minute(s)", "Hour(s)", "Day(s)", "Week(s)", "Month(s)", "Year(s)"];

const COUNTRY_OPTIONS: string[] = [" ", "UNITED STATES", "AFGHANISTAN", "AKROTIRI", "ALBANIA", "ALGERIA", "AMERICAN SAMOA", "ANDORRA", "ANGOLA", "ANGUILLA", "ANTARCTICA", "ANTIGUA AND BARBUDA", "ARGENTINA", "ARMENIA", "ARUBA", "ASHMORE AND CARTIER ISLANDS", "AUSTRALIA", "AUSTRIA", "AZERBAIJAN", "BAHAMAS, THE", "BAHRAIN", "BAKER ISLAND", "BANGLADESH", "BARBADOS", "BASSAS DA INDIA", "BELARUS", "BELGIUM", "BELIZE", "BENIN", "BERMUDA", "BHUTAN", "BOLIVIA", "BONAIRE, SINT EUSTATIUS, AND SABA", "BOSNIA AND HERZEGOVINA", "BOTSWANA", "BOUVET ISLAND", "BRAZIL", "BRITISH INDIAN OCEAN TERRITORY", "BRUNEI", "BULGARIA", "BURKINA FASO", "BURMA", "BURUNDI", "CABO VERDE", "CAMBODIA", "CAMEROON", "CANADA", "CAYMAN ISLANDS", "CENTRAL AFRICAN REPUBLIC", "CHAD", "CHILE", "CHINA", "CHRISTMAS ISLAND", "CLIPPERTON ISLAND", "COCOS (KEELING) ISLANDS", "COLOMBIA", "COMOROS", "CONGO (BRAZZAVILLE)", "CONGO (KINSHASA)", "COOK ISLANDS", "CORAL SEA ISLANDS", "COSTA RICA", "CROATIA", "CUBA", "CURAÇAO", "CYPRUS", "CZECH REPUBLIC", "CÔTE D’IVOIRE", "DENMARK", "DHEKELIA", "DIEGO GARCIA", "DJIBOUTI", "DOMINICA", "DOMINICAN REPUBLIC", "ECUADOR", "EGYPT", "EL SALVADOR", "EQUATORIAL GUINEA", "ERITREA", "ESTONIA", "ETHIOPIA", "EUROPA ISLAND", "FALKLAND ISLANDS (ISLAS MALVINAS)", "FAROE ISLANDS", "FIJI", "FINLAND", "FRANCE", "FRENCH GUIANA", "FRENCH POLYNESIA", "FRENCH SOUTHERN AND ANTARCTIC LANDS", "GABON", "GAMBIA, THE", "GAZA STRIP", "GEORGIA", "GERMANY", "GHANA", "GIBRALTAR", "GLORIOSO ISLANDS", "GREECE", "GREENLAND", "GRENADA", "GUADELOUPE", "GUAM", "GUANTANAMO BAY NAVAL BASE", "GUATEMALA", "GUERNSEY", "GUINEA", "GUINEA-BISSAU", "GUYANA", "HAITI", "HEARD ISLAND AND MCDONALD ISLANDS", "HONDURAS", "HONG KONG", "HOWLAND ISLAND", "HUNGARY", "ICELAND", "INDIA", "INDONESIA", "IRAN", "IRAQ", "IRELAND", "ISLE OF MAN", "ISRAEL", "ITALY", "JAMAICA", "JAN MAYEN", "JAPAN", "JARVIS ISLAND", "JERSEY", "JOHNSTON ATOLL", "JORDAN", "JUAN DE NOVA ISLAND", "KAZAKHSTAN", "KENYA", "KINGMAN REEF", "KIRIBATI", "KOREA, NORTH", "KOREA, SOUTH", "KOSOVO", "KUWAIT", "KYRGYZSTAN", "LAOS", "LATVIA", "LEBANON", "LESOTHO", "LIBERIA", "LIBYA", "LIECHTENSTEIN", "LITHUANIA", "LUXEMBOURG", "MACAU", "MACEDONIA", "MADAGASCAR", "MALAWI", "MALAYSIA", "MALDIVES", "MALI", "MALTA", "MARSHALL ISLANDS", "MARTINIQUE", "MAURITANIA", "MAURITIUS", "MAYOTTE", "MEXICO", "MICRONESIA, FEDERATED STATES OF", "MIDWAY ISLANDS", "MOLDOVA", "MONACO", "MONGOLIA", "MONTENEGRO", "MONTSERRAT", "MOROCCO", "MOZAMBIQUE", "NAMIBIA", "NAURU", "NAVASSA ISLAND", "NEPAL", "NETHERLANDS", "NEW CALEDONIA", "NEW ZEALAND", "NICARAGUA", "NIGER", "NIGERIA", "NIUE", "NORFOLK ISLAND", "NORTHERN MARIANA ISLANDS", "NORWAY", "OMAN", "PAKISTAN", "PALAU", "PALMYRA ATOLL", "PANAMA", "PAPUA NEW GUINEA", "PARACEL ISLANDS", "PARAGUAY", "PERU", "PHILIPPINES", "PITCAIRN ISLANDS", "POLAND", "PORTUGAL", "PUERTO RICO", "QATAR", "REUNION", "ROMANIA", "RUSSIA", "RWANDA", "SAINT BARTHELEMY", "SAINT HELENA, ASCENSION, AND TRISTAN DA CUNHA", "SAINT KITTS AND NEVIS", "SAINT LUCIA", "SAINT MARTIN", "SAINT PIERRE AND MIQUELON", "SAINT VINCENT AND THE GRENADINES", "SAMOA", "SAN MARINO", "SAO TOME AND PRINCIPE", "SAUDI ARABIA", "SENEGAL", "SERBIA", "SEYCHELLES", "SIERRA LEONE", "SINGAPORE", "SINT MAARTEN", "SLOVAKIA", "SLOVENIA", "SOLOMON ISLANDS", "SOMALIA", "SOUTH AFRICA", "SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS", "SOUTH SUDAN", "SPAIN", "SPRATLY ISLANDS", "SRI LANKA", "SUDAN", "SURINAME", "SVALBARD", "SWAZILAND", "SWEDEN", "SWITZERLAND", "SYRIA", "TAIWAN", "TAJIKISTAN", "TANZANIA", "THAILAND", "TIMOR-LESTE", "TOGO", "TOKELAU", "TONGA", "TRINIDAD AND TOBAGO", "TROMELIN ISLAND", "TUNISIA", "TURKEY", "TURKMENISTAN", "TURKS AND CAICOS ISLANDS", "TUVALU", "UGANDA", "UKRAINE", "UNITED ARAB EMIRATES", "UNITED KINGDOM", "UNKNOWN", "URUGUAY", "UZBEKISTAN", "VANUATU", "VATICAN CITY", "VENEZUELA", "VIETNAM", "VIRGIN ISLANDS, BRITISH", "VIRGIN ISLANDS, U.S.", "WAKE ISLAND", "WALLIS AND FUTUNA", "WEST BANK", "WESTERN SAHARA", "YEMEN", "ZAMBIA", "ZIMBABWE"];

const OCCUPATION_OPTIONS: string[] = [" ", "Administrator/Supervisor", "Biomedical Engineer", "Dentist", "Non-Health Professional", "Nurse", "Nurse Practitioner", "Other Health Professional", "Pharmacist", "Physician", "Physician Assistant", "Risk Manager", "Third Party Servicer"];

// The source PDF's own /Opt array pairs the display text "AS NECESSARY - AN"
// (a Frequency value) with an unrelated Strength/Dose unit export code on
// these four fields — never a legitimate answer for a Strength/Dose Unit
// field, even though the manifest reproduces it faithfully in options[]
// above (not corrected there — see the comment above Prod1StrengthUnit).
// The single shared source for every consumer that must refuse it:
// scripts/fill-3500.py's own DISALLOWED_ENUM_VALUES (the canonical,
// PDF-export-enforced definition), src/app/wizard/TopicFields.tsx (filters
// it out of the dropdown), and src/lib/extraction-validator.ts (refuses it
// as a legal narrative-extraction value) — one TS definition, not three.
export const DISALLOWED_ENUM_VALUES: Record<string, ReadonlySet<string>> = {
  "Page4.Prod1.Prod1StrengthUnit": new Set(["AS NECESSARY - AN"]),
  "Page4.Prod1.Prod1DoseUnit": new Set(["AS NECESSARY - AN"]),
  "Page5.Prod2.Prod2StrengthUnit": new Set(["AS NECESSARY - AN"]),
  "Page5.Prod2.Prod2DoseUnit": new Set(["AS NECESSARY - AN"]),
};


// Prod1StrengthUnit/Prod1DoseUnit (and their Prod2 counterparts) carry a real
// defect from the source PDF itself: the second /Opt entry pairs the display
// text "AS NECESSARY - AN" (a Frequency value) with an unrelated Strength/Dose
// unit export code. Reproduced faithfully below, not corrected — this manifest
// enumerates the form as it actually is.
export const FORM_3500_FIELDS: FormFieldSpec[] = [
  {
    id: "Page1.SecA_Patient.PatientIdentifier",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].PatientIdentifier[0]",
    label: "Patient Identifier",
    type: "text",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.AgeValue",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].AgeValue[0]",
    label: "Age",
    type: "text",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.AgeYears",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].AgeYears[0]",
    label: "Age: Year(s)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.AgeMonths",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].AgeMonths[0]",
    label: "Age: Month(s)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.AgeWeeks",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].AgeWeeks[0]",
    label: "Age: Week(s)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.AgeDays",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].AgeDays[0]",
    label: "Age: Day(s)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.DateBirth",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].DateBirth[0]",
    label: "Date of Birth",
    type: "date",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.SexM",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].SexM[0]",
    label: "Sex: Male",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.SexF",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].SexF[0]",
    label: "Sex: Female",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.WeightValue",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].WeightValue[0]",
    label: "Weight",
    type: "text",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.WeightLB",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].WeightLB[0]",
    label: "Weight: lb",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.WeightKG",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].WeightKG[0]",
    label: "Weight: kg",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.RaceAmInd",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].RaceAmInd[0]",
    label: "Race and/or Ethnicity: American Indian or Alaska Native",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.RaceAsian",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].RaceAsian[0]",
    label: "Race and/or Ethnicity: Asian",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.RaceBlack",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].RaceBlack[0]",
    label: "Race and/or Ethnicity: Black or African American",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.EthnicLatino",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].EthnicLatino[0]",
    label: "Race and/or Ethnicity: Hispanic or Latino",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.RaceMiddleEastern",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].RaceMiddleEastern[0]",
    label: "Race and/or Ethnicity: Middle Eastern or North African",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.RacePacific",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].RacePacific[0]",
    label: "Race and/or Ethnicity: Native Hawaiian or Pacific Islander",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.RaceWhite",
    section: "A",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].RaceWhite[0]",
    label: "Race and/or Ethnicity: White",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.RepAdverse",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].RepAdverse[0]",
    label: "Type of Report: Adverse Event",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.RepError",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].RepError[0]",
    label: "Type of Report: Product Use/Medication Error",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.Defects",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].Defects[0]",
    label: "Type of Report: Product Problem (e.g., defects/malfunctions)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.DiffManu",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].DiffManu[0]",
    label: "Type of Report: Problem with Different Manufacturer of Same Medicine",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.Death",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].Death[0]",
    label: "Outcome Attributed to Adverse Event: Death",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.DeathDate",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].DeathDate[0]",
    label: "Outcome Attributed to Adverse Event: Date of Death",
    type: "date",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.Hospital",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].Hospital[0]",
    label: "Outcome Attributed to Adverse Event: Hospitalization (Initial or prolonged)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.LifeThreaten",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].LifeThreaten[0]",
    label: "Outcome Attributed to Adverse Event: Life-threatening",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.Disability",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].Disability[0]",
    label: "Outcome Attributed to Adverse Event: Disability or Permanent Damage",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.ReqdInter",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].ReqdInter[0]",
    label: "Outcome Attributed to Adverse Event: Required Intervention to Prevent Permanent Impairment/Damage",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.Congenital",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].Congenital[0]",
    label: "Outcome Attributed to Adverse Event: Congenital Anomaly/Birth Defects",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.OtherEvents",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].OtherEvents[0]",
    label: "Outcome Attributed to Adverse Event: Other Serious or Important Medical Events",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.EventDate",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].EventDate[0]",
    label: "Date of Event",
    type: "date",
    required: false,
  },
  {
    id: "Page1.SecA_Patient.ReportDate",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page1[0].SecA_Patient[0].ReportDate[0]",
    label: "Date of this Report",
    type: "date",
    required: false,
  },
  {
    id: "Page2.SecB_Adverse.DescEvent",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page2[0].SecB_Adverse[0].DescEvent[0]",
    label: "Describe Event, Problem or Product Use/Medication Error",
    type: "text",
    required: false,
  },
  {
    id: "Page3.Sec6Data.OtherHistory",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].Sec6Data[0].OtherHistory[0]",
    label: "Other Relevant History, Including Preexisting Medical Conditions",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row1.TestData1",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row1[0].TestData1[0]",
    label: "Relevant Test/Laboratory Data: Row 1 — Test/Lab Data",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row1.TLowRange1",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row1[0].TLowRange1[0]",
    label: "Relevant Test/Laboratory Data: Row 1 — Low Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row1.THighRange1",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row1[0].THighRange1[0]",
    label: "Relevant Test/Laboratory Data: Row 1 — High Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row1.TDate1",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row1[0].TDate1[0]",
    label: "Relevant Test/Laboratory Data: Row 1 — Date",
    type: "date",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row2.TestData2",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row2[0].TestData2[0]",
    label: "Relevant Test/Laboratory Data: Row 2 — Test/Lab Data",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row2.TLowRange2",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row2[0].TLowRange2[0]",
    label: "Relevant Test/Laboratory Data: Row 2 — Low Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row2.THighRange2",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row2[0].THighRange2[0]",
    label: "Relevant Test/Laboratory Data: Row 2 — High Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row2.TDate2",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row2[0].TDate2[0]",
    label: "Relevant Test/Laboratory Data: Row 2 — Date",
    type: "date",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row3.TestData3",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row3[0].TestData3[0]",
    label: "Relevant Test/Laboratory Data: Row 3 — Test/Lab Data",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row3.TLowRange3",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row3[0].TLowRange3[0]",
    label: "Relevant Test/Laboratory Data: Row 3 — Low Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row3.THighRange3",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row3[0].THighRange3[0]",
    label: "Relevant Test/Laboratory Data: Row 3 — High Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row4.TestData4",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row4[0].TestData4[0]",
    label: "Relevant Test/Laboratory Data: Row 4 — Test/Lab Data",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row4.TLowRange4",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row4[0].TLowRange4[0]",
    label: "Relevant Test/Laboratory Data: Row 4 — Low Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row4.THighRange4",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row4[0].THighRange4[0]",
    label: "Relevant Test/Laboratory Data: Row 4 — High Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row5.TestData5",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row5[0].TestData5[0]",
    label: "Relevant Test/Laboratory Data: Row 5 — Test/Lab Data",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row5.TLowRange5",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row5[0].TLowRange5[0]",
    label: "Relevant Test/Laboratory Data: Row 5 — Low Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row5.THighRange5",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row5[0].THighRange5[0]",
    label: "Relevant Test/Laboratory Data: Row 5 — High Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row6.TestData6",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row6[0].TestData6[0]",
    label: "Relevant Test/Laboratory Data: Row 6 — Test/Lab Data",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row6.TLowRange6",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row6[0].TLowRange6[0]",
    label: "Relevant Test/Laboratory Data: Row 6 — Low Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row6.THighRange6",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row6[0].THighRange6[0]",
    label: "Relevant Test/Laboratory Data: Row 6 — High Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row7.TestData7",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row7[0].TestData7[0]",
    label: "Relevant Test/Laboratory Data: Row 7 — Test/Lab Data",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row7.TLowRange7",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row7[0].TLowRange7[0]",
    label: "Relevant Test/Laboratory Data: Row 7 — Low Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.TestData8",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].TestData8[0]",
    label: "Relevant Test/Laboratory Data: Row 8 — Test/Lab Data",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.TLowRange8",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].TLowRange8[0]",
    label: "Relevant Test/Laboratory Data: Row 8 — Low Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.THighRange8",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].THighRange8[0]",
    label: "Relevant Test/Laboratory Data: Row 8 — High Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.TDate8",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].TDate8[0]",
    label: "Relevant Test/Laboratory Data: Row 8 — Date",
    type: "date",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.THighRange7",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].THighRange7[0]",
    label: "Relevant Test/Laboratory Data: Row 7 — High Test Range",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.TDate3",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].TDate3[0]",
    label: "Relevant Test/Laboratory Data: Row 3 — Date",
    type: "date",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.TDate4",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].TDate4[0]",
    label: "Relevant Test/Laboratory Data: Row 4 — Date",
    type: "date",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.TDate5",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].TDate5[0]",
    label: "Relevant Test/Laboratory Data: Row 5 — Date",
    type: "date",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.TDate6",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].TDate6[0]",
    label: "Relevant Test/Laboratory Data: Row 6 — Date",
    type: "date",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row8.TDate7",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row8[0].TDate7[0]",
    label: "Relevant Test/Laboratory Data: Row 7 — Date",
    type: "date",
    required: false,
  },
  {
    id: "Page3.AdditionalComments",
    section: "B",
    pdfFieldName: "topmostSubform[0].Page3[0].AdditionalComments[0]",
    label: "Additional Comments",
    type: "text",
    required: false,
  },
  {
    id: "Page3.TestDataTable.Row7.PicYes",
    section: "C",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].Row7[0].PicYes[0]",
    label: "Do you have a picture of the product?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page3.TestDataTable.ReturnDate",
    section: "C",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].ReturnDate[0]",
    label: "Product Available for Evaluation?: Returned to Manufacturer on",
    type: "date",
    required: false,
  },
  {
    id: "Page3.TestDataTable.EvalRetd",
    section: "C",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].EvalRetd[0]",
    label: "Product Available for Evaluation?: Returned to Manufacturer",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page3.TestDataTable.EvalNo",
    section: "C",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].EvalNo[0]",
    label: "Product Available for Evaluation?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page3.TestDataTable.EvalYes",
    section: "C",
    pdfFieldName: "topmostSubform[0].Page3[0].TestDataTable[0].EvalYes[0]",
    label: "Product Available for Evaluation?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Name",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Name[0]",
    label: "Suspect Product #1: Name, Strength, Manufacturer/Compounder: Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Strength",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Strength[0]",
    label: "Suspect Product #1: Name, Strength, Manufacturer/Compounder: Strength",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1StrengthUnit",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1StrengthUnit[0]",
    label: "Suspect Product #1: Name, Strength, Manufacturer/Compounder: Unit",
    type: "enum",
    required: false,
    options: UNIT_OPTIONS,
  },
  {
    id: "Page4.Prod1.Prod1NDC_ID",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1NDC_ID[0]",
    label: "Suspect Product #1: Name, Strength, Manufacturer/Compounder: NDC # or Unique ID",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1ManuComp",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1ManuComp[0]",
    label: "Suspect Product #1: Name, Strength, Manufacturer/Compounder: Manufacturer/Compounder Name",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1LotNum",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1LotNum[0]",
    label: "Suspect Product #1: Name, Strength, Manufacturer/Compounder: Lot #",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Dose",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Dose[0]",
    label: "Suspect Product #1: Dose or Amount: Dose or Amount",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1DoseUnit",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1DoseUnit[0]",
    label: "Suspect Product #1: Dose or Amount: Unit",
    type: "enum",
    required: false,
    options: UNIT_OPTIONS,
  },
  {
    id: "Page4.Prod1.Prod1Freq",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Freq[0]",
    label: "Suspect Product #1: Dose or Amount: Frequency",
    type: "enum",
    required: false,
    options: FREQUENCY_OPTIONS,
  },
  {
    id: "Page4.Prod1.Prod1FreqOther",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1FreqOther[0]",
    label: "Suspect Product #1: Dose or Amount: Other Frequency",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Route",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Route[0]",
    label: "Suspect Product #1: Dose or Amount: Route",
    type: "enum",
    required: false,
    options: ROUTE_OPTIONS,
  },
  {
    id: "Page4.Prod1.Prod1RouteOther",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1RouteOther[0]",
    label: "Suspect Product #1: Dose or Amount: Other Route",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1TherapyStartDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1TherapyStartDate[0]",
    label: "Suspect Product #1: Treatment/Therapy/Usage Dates: Therapy/Usage started on",
    type: "date",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1TherapyStopDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1TherapyStopDate[0]",
    label: "Suspect Product #1: Treatment/Therapy/Usage Dates: Therapy/Usage stopped on",
    type: "date",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1TherapyReduceDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1TherapyReduceDate[0]",
    label: "Suspect Product #1: Treatment/Therapy/Usage Dates: Dose reduced on",
    type: "date",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1TherapyDuration",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1TherapyDuration[0]",
    label: "Suspect Product #1: Treatment/Therapy/Usage Dates: Duration",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1TherapyDurUnit",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1TherapyDurUnit[0]",
    label: "Suspect Product #1: Treatment/Therapy/Usage Dates: Duration Unit",
    type: "enum",
    required: false,
    options: DURATION_UNIT_OPTIONS,
  },
  {
    id: "Page4.Prod1.Prod1TherapyOngoingYes",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1TherapyOngoingYes[0]",
    label: "Suspect Product #1: Is therapy/usage still on-going?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1TherapyOngoingNo",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1TherapyOngoingNo[0]",
    label: "Suspect Product #1: Is therapy/usage still on-going?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Diagnosis",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Diagnosis[0]",
    label: "Suspect Product #1: Diagnosis for use (Indication)",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Compounded",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Compounded[0]",
    label: "Suspect Product #1: Product Type: Compounded product (By a Pharmacy or an Outsourcing Facility)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1CosmProf",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1CosmProf[0]",
    label: "Suspect Product #1: Product Type: Cosmetics for professional use only",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1ExpDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1ExpDate[0]",
    label: "Suspect Product #1: Expiration Date",
    type: "date",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1AbatedYes",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1AbatedYes[0]",
    label: "Suspect Product #1: Event Abated after use Stopped or Dose Reduced?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1AbatedNo",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1AbatedNo[0]",
    label: "Suspect Product #1: Event Abated after use Stopped or Dose Reduced?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1AbatedNA",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1AbatedNA[0]",
    label: "Suspect Product #1: Event Abated after use Stopped or Dose Reduced?: Doesn't apply",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1ReappearYes",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1ReappearYes[0]",
    label: "Suspect Product #1: Event Reappeared after Reintroduction?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1ReappearNo",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1ReappearNo[0]",
    label: "Suspect Product #1: Event Reappeared after Reintroduction?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1ReappearNA",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1ReappearNA[0]",
    label: "Suspect Product #1: Event Reappeared after Reintroduction?: Doesn't apply",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1PlaceName",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1PlaceName[0]",
    label: "Suspect Product #1: Place and Date of Purchase: Name",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Address",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Address[0]",
    label: "Suspect Product #1: Place and Date of Purchase: Address",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Country",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Country[0]",
    label: "Suspect Product #1: Place and Date of Purchase: Country",
    type: "enum",
    required: false,
    options: COUNTRY_OPTIONS,
  },
  {
    id: "Page4.Prod1.Prod1City",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1City[0]",
    label: "Suspect Product #1: Place and Date of Purchase: City",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1State",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1State[0]",
    label: "Suspect Product #1: Place and Date of Purchase: State/Province/Region",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.ZipCode",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].ZipCode[0]",
    label: "Suspect Product #1: Place and Date of Purchase: ZIP/Postal Code",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Website",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Website[0]",
    label: "Suspect Product #1: Place and Date of Purchase: Website (If purchased online)",
    type: "text",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1PurchaseDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1PurchaseDate[0]",
    label: "Suspect Product #1: Place and Date of Purchase: Purchase Date",
    type: "date",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Brand",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Brand[0]",
    label: "Suspect Product #1: Product Type: Brand",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Generic",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Generic[0]",
    label: "Suspect Product #1: Product Type: Generic or Biosimilar",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1OTC",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1OTC[0]",
    label: "Suspect Product #1: Product Type: Over-the-Counter (OTC)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1PdtOther",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1PdtOther[0]",
    label: "Suspect Product #1: Product Type: Other",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1Cannabi",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1Cannabi[0]",
    label: "Suspect Product #1: Product Type: Cannabinoid hemp products (Such as products containing CBD)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page4.Prod1.Prod1CosRetail",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page4[0].Prod1[0].Prod1CosRetail[0]",
    label: "Suspect Product #1: Product Type: Cosmetics sold on a retail basis",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2Name",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Name[0]",
    label: "Suspect Product #2: Name, Strength, Manufacturer/Compounder: Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2Strength",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Strength[0]",
    label: "Suspect Product #2: Name, Strength, Manufacturer/Compounder: Strength",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2StrengthUnit",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2StrengthUnit[0]",
    label: "Suspect Product #2: Name, Strength, Manufacturer/Compounder: Unit",
    type: "enum",
    required: false,
    options: UNIT_OPTIONS,
  },
  {
    id: "Page5.Prod2.Prod2NDC_ID",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2NDC_ID[0]",
    label: "Suspect Product #2: Name, Strength, Manufacturer/Compounder: NDC # or Unique ID",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2ManuComp",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2ManuComp[0]",
    label: "Suspect Product #2: Name, Strength, Manufacturer/Compounder: Manufacturer/Compounder Name",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2LotNum",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2LotNum[0]",
    label: "Suspect Product #2: Name, Strength, Manufacturer/Compounder: Lot #",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2Dose",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Dose[0]",
    label: "Suspect Product #2: Dose or Amount: Dose or Amount",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2DoseUnit",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2DoseUnit[0]",
    label: "Suspect Product #2: Dose or Amount: Unit",
    type: "enum",
    required: false,
    options: UNIT_OPTIONS,
  },
  {
    id: "Page5.Prod2.Prod2Freq",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Freq[0]",
    label: "Suspect Product #2: Dose or Amount: Frequency",
    type: "enum",
    required: false,
    options: FREQUENCY_OPTIONS,
  },
  {
    id: "Page5.Prod2.Prod2FreqOther",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2FreqOther[0]",
    label: "Suspect Product #2: Dose or Amount: Other Frequency",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2Route",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Route[0]",
    label: "Suspect Product #2: Dose or Amount: Route",
    type: "enum",
    required: false,
    options: ROUTE_OPTIONS,
  },
  {
    id: "Page5.Prod2.Prod2RouteOther",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2RouteOther[0]",
    label: "Suspect Product #2: Dose or Amount: Other Route",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2TherapyStartDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2TherapyStartDate[0]",
    label: "Suspect Product #2: Treatment/Therapy/Usage Dates: Therapy/Usage started on",
    type: "date",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2TherapyStopDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2TherapyStopDate[0]",
    label: "Suspect Product #2: Treatment/Therapy/Usage Dates: Therapy/Usage stopped on",
    type: "date",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2TherapyReduceDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2TherapyReduceDate[0]",
    label: "Suspect Product #2: Treatment/Therapy/Usage Dates: Dose reduced on",
    type: "date",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2TherapyDuration",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2TherapyDuration[0]",
    label: "Suspect Product #2: Treatment/Therapy/Usage Dates: Duration",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2TherapyDurUnit",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2TherapyDurUnit[0]",
    label: "Suspect Product #2: Treatment/Therapy/Usage Dates: Duration Unit",
    type: "enum",
    required: false,
    options: DURATION_UNIT_OPTIONS,
  },
  {
    id: "Page5.Prod2.Prod2TherapyOngoingYes",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2TherapyOngoingYes[0]",
    label: "Suspect Product #2: Is therapy/usage still on-going?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2TherapyOngoingNo",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2TherapyOngoingNo[0]",
    label: "Suspect Product #2: Is therapy/usage still on-going?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2Diagnosis",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Diagnosis[0]",
    label: "Suspect Product #2: Diagnosis for use (Indication)",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2Compounded",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Compounded[0]",
    label: "Suspect Product #2: Product Type: Compounded product (By a Pharmacy or an Outsourcing Facility)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.pdt2CosmProf",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].pdt2CosmProf[0]",
    label: "Suspect Product #2: Product Type: Cosmetics for professional use only",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2ExpDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2ExpDate[0]",
    label: "Suspect Product #2: Expiration Date",
    type: "date",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2AbatedYes",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2AbatedYes[0]",
    label: "Suspect Product #2: Event Abated after use Stopped or Dose Reduced?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2AbatedNo",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2AbatedNo[0]",
    label: "Suspect Product #2: Event Abated after use Stopped or Dose Reduced?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2AbatedNA",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2AbatedNA[0]",
    label: "Suspect Product #2: Event Abated after use Stopped or Dose Reduced?: Doesn't apply",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2ReappearYes",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2ReappearYes[0]",
    label: "Suspect Product #2: Event Reappeared after Reintroduction?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2ReappearNo",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2ReappearNo[0]",
    label: "Suspect Product #2: Event Reappeared after Reintroduction?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2ReappearNA",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2ReappearNA[0]",
    label: "Suspect Product #2: Event Reappeared after Reintroduction?: Doesn't apply",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2PlaceName",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2PlaceName[0]",
    label: "Suspect Product #2: Place and Date of Purchase: Name",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2Address",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Address[0]",
    label: "Suspect Product #2: Place and Date of Purchase: Address",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Pdt2Country",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Pdt2Country[0]",
    label: "Suspect Product #2: Place and Date of Purchase: Country",
    type: "enum",
    required: false,
    options: COUNTRY_OPTIONS,
  },
  {
    id: "Page5.Prod2.Pdt2City",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Pdt2City[0]",
    label: "Suspect Product #2: Place and Date of Purchase: City",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Pdt2State",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Pdt2State[0]",
    label: "Suspect Product #2: Place and Date of Purchase: State/Province/Region",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.ZipCode",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].ZipCode[0]",
    label: "Suspect Product #2: Place and Date of Purchase: ZIP/Postal Code",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Pdt2Website",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Pdt2Website[0]",
    label: "Suspect Product #2: Place and Date of Purchase: Website (If purchased online)",
    type: "text",
    required: false,
  },
  {
    id: "Page5.Prod2.Pdt2PurchaseDate",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Pdt2PurchaseDate[0]",
    label: "Suspect Product #2: Place and Date of Purchase: Purchase Date",
    type: "date",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2Brand",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Brand[0]",
    label: "Suspect Product #2: Product Type: Brand",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2Generic",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2Generic[0]",
    label: "Suspect Product #2: Product Type: Generic or Biosimilar",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Prod2OTC",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Prod2OTC[0]",
    label: "Suspect Product #2: Product Type: Over-the-Counter (OTC)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Pdt2PdtOther",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Pdt2PdtOther[0]",
    label: "Suspect Product #2: Product Type: Other",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Pdt2Cannabi",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Pdt2Cannabi[0]",
    label: "Suspect Product #2: Product Type: Cannabinoid hemp products (Such as products containing CBD)",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page5.Prod2.Pdt2CosRetail",
    section: "D",
    pdfFieldName: "topmostSubform[0].Page5[0].Prod2[0].Pdt2CosRetail[0]",
    label: "Suspect Product #2: Product Type: Cosmetics sold on a retail basis",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page6.SecE_Device.BrandName",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].BrandName[0]",
    label: "Brand Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.CommName",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].CommName[0]",
    label: "Common Device Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.Procode",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].Procode[0]",
    label: "Procode",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ManuName",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ManuName[0]",
    label: "Manufacturer Name, City and State",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ModelNum",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ModelNum[0]",
    label: "Model #",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.LotNum",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].LotNum[0]",
    label: "Lot #",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.CatNum",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].CatNum[0]",
    label: "Catalog #",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ExpDate",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ExpDate[0]",
    label: "Expiration Date",
    type: "date",
    required: false,
  },
  {
    id: "Page6.SecE_Device.SerialNum",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].SerialNum[0]",
    label: "Serial #",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.UDInum",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].UDInum[0]",
    label: "Unique Device Identifier (UDI) #",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.HealthPro",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].HealthPro[0]",
    label: "Operator of device: Health Professional",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page6.SecE_Device.PatientCons",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].PatientCons[0]",
    label: "Operator of device: Patient/Consumer",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page6.SecE_Device.OperatorOther",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].OperatorOther[0]",
    label: "Operator of device: Other",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ImplantDate",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ImplantDate[0]",
    label: "If Implanted, Give Date",
    type: "date",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ExplantDate",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ExplantDate[0]",
    label: "If Explanted, Give Date",
    type: "date",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ReuseYes",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ReuseYes[0]",
    label: "Is this a single-use device that was reprocessed and reused on a patient?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ReuseNo",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ReuseNo[0]",
    label: "Is this a single-use device that was reprocessed and reused on a patient?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ReprocInfo",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ReprocInfo[0]",
    label: "If Yes to Item 7a, Enter Name, Address of Reprocessor",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ServicedYes",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ServicedYes[0]",
    label: "Was this device ever serviced by a third-party servicer?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ServicedNo",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ServicedNo[0]",
    label: "Was this device ever serviced by a third-party servicer?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page6.SecE_Device.ServiceUnk",
    section: "E",
    pdfFieldName: "topmostSubform[0].Page6[0].SecE_Device[0].ServiceUnk[0]",
    label: "Was this device ever serviced by a third-party servicer?: Unknown",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row1.Prod1",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row1[0].Prod1[0]",
    label: "Product names and therapy dates: Row 1 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row1.Start1",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row1[0].Start1[0]",
    label: "Product names and therapy dates: Row 1 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row1.End1",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row1[0].End1[0]",
    label: "Product names and therapy dates: Row 1 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row2.Prod2",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row2[0].Prod2[0]",
    label: "Product names and therapy dates: Row 2 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row2.Start2",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row2[0].Start2[0]",
    label: "Product names and therapy dates: Row 2 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row2.End2",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row2[0].End2[0]",
    label: "Product names and therapy dates: Row 2 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row3.Prod3",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row3[0].Prod3[0]",
    label: "Product names and therapy dates: Row 3 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row3.Start3",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row3[0].Start3[0]",
    label: "Product names and therapy dates: Row 3 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row3.Cell4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row3[0].Cell4[0]",
    label: "Product names and therapy dates: Row 3 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row4.Prod4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row4[0].Prod4[0]",
    label: "Product names and therapy dates: Row 4 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row4.Start4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row4[0].Start4[0]",
    label: "Product names and therapy dates: Row 4 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row4.Cell4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row4[0].Cell4[0]",
    label: "Product names and therapy dates: Row 4 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row5.Prod5",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row5[0].Prod5[0]",
    label: "Product names and therapy dates: Row 5 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row5.Start5",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row5[0].Start5[0]",
    label: "Product names and therapy dates: Row 5 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row5.Cell4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row5[0].Cell4[0]",
    label: "Product names and therapy dates: Row 5 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row6.Prod6",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row6[0].Prod6[0]",
    label: "Product names and therapy dates: Row 6 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row6.Start6",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row6[0].Start6[0]",
    label: "Product names and therapy dates: Row 6 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row6.Cell4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row6[0].Cell4[0]",
    label: "Product names and therapy dates: Row 6 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row7.Prod7",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row7[0].Prod7[0]",
    label: "Product names and therapy dates: Row 7 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row7.Start7",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row7[0].Start7[0]",
    label: "Product names and therapy dates: Row 7 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row7.Cell4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row7[0].Cell4[0]",
    label: "Product names and therapy dates: Row 7 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row8.Prod8",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row8[0].Prod8[0]",
    label: "Product names and therapy dates: Row 8 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row8.Start8",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row8[0].Start8[0]",
    label: "Product names and therapy dates: Row 8 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row8.Cell4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row8[0].Cell4[0]",
    label: "Product names and therapy dates: Row 8 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row9.Prod9",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row9[0].Prod9[0]",
    label: "Product names and therapy dates: Row 9 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row9.Start9",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row9[0].Start9[0]",
    label: "Product names and therapy dates: Row 9 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row9.Cell4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row9[0].Cell4[0]",
    label: "Product names and therapy dates: Row 9 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row10.Prod10",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row10[0].Prod10[0]",
    label: "Product names and therapy dates: Row 10 — Product Name",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row10.Start10",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row10[0].Start10[0]",
    label: "Product names and therapy dates: Row 10 — Therapy Start Date",
    type: "text",
    required: false,
  },
  {
    id: "Page6.SecF_Other.Table1.Row10.Cell4",
    section: "F",
    pdfFieldName: "topmostSubform[0].Page6[0].SecF_Other[0].Table1[0].Row10[0].Cell4[0]",
    label: "Product names and therapy dates: Row 10 — Therapy End Date",
    type: "text",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.LastName",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].LastName[0]",
    label: "Name and Address: Last Name",
    type: "text",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.FirstName",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].FirstName[0]",
    label: "Name and Address: First Name",
    type: "text",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.Address",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].Address[0]",
    label: "Name and Address: Address",
    type: "text",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.City",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].City[0]",
    label: "Name and Address: City",
    type: "text",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.State",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].State[0]",
    label: "Name and Address: State/Province/Region",
    type: "text",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.ZipCode",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].ZipCode[0]",
    label: "Name and Address: ZIP/Postal Code",
    type: "text",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.Country",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].Country[0]",
    label: "Name and Address: Country",
    type: "enum",
    required: false,
    options: COUNTRY_OPTIONS,
  },
  {
    id: "Page7.SecG_Reporter.PhoneNum",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].PhoneNum[0]",
    label: "Phone #",
    type: "text",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.Email",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].Email[0]",
    label: "Email",
    type: "text",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.ProYes",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].ProYes[0]",
    label: "Health Professional?: Yes",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.ProNo",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].ProNo[0]",
    label: "Health Professional?: No",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.Occupation",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].Occupation[0]",
    label: "Occupation",
    type: "enum",
    required: false,
    options: OCCUPATION_OPTIONS,
  },
  {
    id: "Page7.SecG_Reporter.ManuComp",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].ManuComp[0]",
    label: "Also Reported to: Manufacturer/Compounder",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.UserFac",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].UserFac[0]",
    label: "Also Reported to: User Facility",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.DistImp",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].DistImp[0]",
    label: "Also Reported to: Distributor/Importer",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.IdentityNo",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].IdentityNo[0]",
    label: "If you do NOT want your identity disclosed to the manufacturer, please mark this box",
    type: "checkbox",
    required: false,
  },
  {
    id: "Page7.SecG_Reporter.Packer",
    section: "G",
    pdfFieldName: "topmostSubform[0].Page7[0].SecG_Reporter[0].Packer[0]",
    label: "Also Reported to: Packer",
    type: "checkbox",
    required: false,
  },
];
